DROP PROCEDURE IF EXISTS dbo.FI_SP_PesqBeneficiario;
GO

CREATE PROC FI_SP_PesqBeneficiario
	@CLIENTEID BIGINT
AS
BEGIN
	SELECT ID, CPF, NOME, IDCLIENTE FROM BENEFICIARIOS WITH(NOLOCK) WHERE IDCLIENTE = @CLIENTEID
END